<a href="https://colab.research.google.com/github/VicktorHg/intro_numpy.pandas.scikitlearn/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Intro to numpy**

In [ ]:
import numpy as np
# numpy - numeric python
# ndarray = n-dimensional array

In [ ]:
#Usamos primero una lista normal en python
list1 = [1,2,3,4,5]
print(list1)
print(list1[0])

list2 = ["john elder", 41, list1, True]
print(list2)

[1, 2, 3, 4, 5]
1
['john elder', 41, [1, 2, 3, 4, 5], True]


In [ ]:
#lista en numpy
np1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(np1)
print(np1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10]
(11,)


In [ ]:
#range
np2 = np.arange(12)
print(np2, "\n")

#step
np3 = np.arange(0,10,2)
print(np3, "\n")

#zeros
np4 = np.zeros(12)
print(np4, "\n")

#multidimensional zeros
np5 = np.zeros((5,5))
print(np5, "\n")

#full
np6 = np.full((5,5), 6)
print(np6, "\n")

#convert pythin list to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[0 2 4 6 8] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]] 

[1 2 3 4 5]


**Slicing numpy arrays**



In [ ]:
#slicing numpy arrays
#return 1,2,3,4
print(np1[1:5], "\n")

#return from somethin till the end of the array
print(np1[3:], "\n")

#return negative slices
print(np1[-3:-1], "\n")

#steps
print(np1[1:5], "\n") #1 to 4
print(np1[1:5:2], "\n") #1 to 3 in steps of 2

#steps on the entire array
print(np1[::2], "\n")
print(np1[::3], "\n")

#slice a 2-d array
np9 = np.array([[1,2,3,4,5],[6,7,8,9,10]], "\n")
#the first array is 0, and the second is 1

#pull out a single item
print(np9[1,2], "\n")

#slice a 2-d array 2,3
print(np9[0:1, 1:3], "\n")
#slice from both rows 2,3 and 7,8
print(np9[0:2, 1:3], "\n")

[1 2 3 4] 

[ 3  4  5  6  7  8  9 10] 

[8 9] 

[1 2 3 4] 

[1 3] 

[ 0  2  4  6  8 10] 

[0 3 6 9] 

8 

[[2 3]] 

[[2 3]
 [7 8]] 



**Numpy universal functions**

In [ ]:
#universal functions in numpy
#square route of each element
print(np.sqrt(np9), "\n")

#absolute value
np10 = np.array([-3,-2,-1,0,1,2,3])
print(np.absolute(np10), "\n")

#exponentials
#It calculates ex for each x in your list where e is Euler's number (approximately 2.718)
print(np.exp(np10), "\n")

#min/max
print(np.min(np10))
print(np.max(np10), "\n")

#sign positive or negative
np11 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sign(np11), "\n")

#trig sin/cos/log
print(np.sin(np11), "\n")
print(np.cos(np11), "\n")
print(np.log(np11), "\n")

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]] 

[3 2 1 0 1 2 3] 

[ 0.04978707  0.13533528  0.36787944  1.          2.71828183  7.3890561
 20.08553692] 

-3
3 

[1 1 1 1 1 1 1 1 1 1] 

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111] 

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153] 

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509] 



**Numpy array copy vs view**

In [ ]:
#copy vs view
#declare a new array

np12 = np.array([0,1,2,3,4,5])

'''
#create a view
np13 = np12.view()

print(f'Original NP1 {np12}')
print(f'Original NP2 {np13}', "\n")

np12[0] = 41

print(f'Changed NP1 {np12}')
print(f'Original NP2 {np12}', "\n")
'''

#create a copy

np13 = np12.copy()
print(f'Original NP1 {np12}')
print(f'Original NP2 {np13}', "\n")

np12[0] =41

print(f'Changed NP1 {np12}')
print(f'Original NP2 {np13}', "\n")

Original NP1 [0 1 2 3 4 5]
Original NP2 [0 1 2 3 4 5] 

Changed NP1 [41  1  2  3  4  5]
Original NP2 [0 1 2 3 4 5] 



**Shape and Rechape numpy arrays**

In [ ]:
#create 1-D numpy array and get shape
np14 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np14)
print("shape: ", np14.shape, "\n")

#create 2-D (rows/columns)
np15 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np15)
print("shape: ", np15.shape, "\n")

#reshape 1-D in 2-D
np16 = np14.reshape(3,4)
print(np16)
print("shape: ", np16.shape, "\n")

#reshape 3-D
np17 = np14.reshape(2,3,2)
print(np17)
print("shape: ", np17.shape, "\n")

#flatten to 1-D
np18 = np17.reshape(-1)
print(np18)
print("shape: ", np18.shape, "\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape:  (12,) 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
shape:  (2, 6) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape:  (3, 4) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
shape:  (2, 3, 2) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape:  (12,) 



**Iterating through numpy arrays**

In [ ]:
#array 1-D
import numpy as np
np20 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np20:
  print(x)

1
2
3
4
5
6
7
8
9
10


In [ ]:
np21 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np21:
  print(x, "\n")
  for y in x:
    print(y)

[1 2 3 4 5] 

1
2
3
4
5
[ 6  7  8  9 10] 

6
7
8
9
10


In [ ]:
# 3-D array
np23 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np23:
  #print(x)
  for y in x:
   # print(y)
    for z in y:
      print(y)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[7 8 9]
[7 8 9]
[7 8 9]
[10 11 12]
[10 11 12]
[10 11 12]


In [ ]:
#use np.nditer

for x in np.nditer(np23):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


**Sorting numpy arrays the right way**

In [7]:
import numpy as np
#np.sort()
np1 = np.array([6,7,4,9,0,2,1])
print(np.sort(np1), "\n")

#numerical
np2 = np.array(["john", "Tina", "Aaron", "Vicktor", "Marielle", "Zed"])
print(np.sort(np2), "\n")

#booleans
np3 = np.array(([True, False, True, False]))
print(np.sort(np3), "\n")

#return a copy not change the original
print((np1))
print(np.sort(np1))
print((np1), "\n")

#2-D

np4 = np.array([[34,87,1,],[87,99,45,]])
print(np.sort(np4))

[0 1 2 4 6 7 9] 

['Aaron' 'Marielle' 'Tina' 'Vicktor' 'Zed' 'john'] 

[False False  True  True] 

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1] 

[[ 1 34 87]
 [45 87 99]]


In [13]:
#search
np5 = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.where(np5 == 3)
print(np5)
print(x[0])
print(np5[x[0]], "\n")

#return even items

y = np.where(np5 % 2 == 0)
print(np5)
print("their position are: ", y[0])
print("the numbers are: ", np5[y[0]], "\n")

#return odd items

z = np.where(np5 % 2 == 1)
print(np5)
print("their position are: ", z[0])
print("the numbers are: ", np5[z[0]], "\n")

[ 1  2  3  4  5  6  7  8  9 10]
[2]
[3] 

[ 1  2  3  4  5  6  7  8  9 10]
their position are:  [1 3 5 7 9]
the numbers are:  [ 2  4  6  8 10] 

[ 1  2  3  4  5  6  7  8  9 10]
their position are:  [0 2 4 6 8]
the numbers are:  [1 3 5 7 9] 



In [22]:
#filtering numpy arrays with boolean index list
np6 = np.array([1,2,3,4,5,6,7,8,9,10])

x = [True, True, False, False, False, False, False, False, False, False]
print(np6)
print(np6[x], "\n")

#filter
filtered = []
for thing in np6:
  if thing % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

print(np6)
print(filtered)
print(np6[filtered], "\n")

#another way

print(np6)
print(filtered)
print(np6[filtered], "\n")

#shortcut
filtered = np6 % 2 == 1
print(np6)
print(filtered)
print(np6[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[1 2] 

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10] 

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10] 

[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False  True False  True False]
[1 3 5 7 9]
